database:
  driverClass: com.mysql.cj.jdbc.Driver
  user: root
  password: root
  url: jdbc:mysql://localhost/tokenservice
host: localhost
port: 8080
server:
        applicationConnectors:
          - type: http
                # The port the application will listen on
            port: 8181
        adminConnectors:
          - type: http
                # The admin port
            port: 8282
